### ISSUE TITLE
unable to start ctfnote_api

### ISSUE THREAD

**Issue by KristinnVikarJ** [TFNS/CTFNote#139]
Whenever I start ctfnote_api I get this error
```
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: A type naming conflict has occurred - two entities have tried to define the same type 'UsersOrderBy'.

  The first entity was:

    Adding connection "orderBy" argument for table "ctfnote"."Users". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON TABLE "ctfnote"."Users" IS E'@name newNameHere';

  The second entity was:

    Adding connection "orderBy" argument for view "ctfnote"."users". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON VIEW "ctfnote"."users" IS E'@name newNameHere';
    at Object.addType (/app/node_modules/graphile-build/node8plus/makeNewBuild.js:253:17)
    at Object.newWithHooks (/app/node_modules/graphile-build/node8plus/makeNewBuild.js:730:14)
    at /app/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:34:7
    at Array.forEach (<anonymous>)
    at /app/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:27:38
    at SchemaBuilder.applyHooks (/app/node_modules/graphile-build/node8plus/SchemaBuilder.js:264:20)
    at SchemaBuilder.createBuild (/app/node_modules/graphile-build/node8plus/SchemaBuilder.js:325:10)
    at SchemaBuilder.buildSchema (/app/node_modules/graphile-build/node8plus/SchemaBuilder.js:333:26)
    at Object.exports.createPostGraphileSchema (/app/node_modules/postgraphile-core/node8plus/index.js:226:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

error Command failed with exit code 34.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This also happens on a clean build of CTFNote, I've tried version 2.0.0, 2.0.1 and up to date on master

**Comment by XeR** [comment]
Does this happen at build time ? Can you reproduce the error with `docker-compose build --no-cache api` ?

**Comment by KristinnVikarJ** [comment]
Ah sorry, I was in the middle of complete reinstall of docker, completely reinstalling it with no volumes, images, cache etc made it finally work
But this started happening out of the blue after the machine itself rebooted

**Comment by XeR** [comment]
I'm a bit confused.
Are you saying that it used to work and it suddenly stopped working after a reboot ? Or do you say it happened after a reboot and that you fixed it by wiping Docker's state ?
If 2, can we close this issue ?

**Comment by KristinnVikarJ** [comment]
The second one, a reboot caused this issue to happen but after wiping docker completely and rebuilding it works now
