### ISSUE TITLE
Importing tasks does not check for unicity

### ISSUE THREAD

**Issue by XeR** [TFNS/CTFNote#25]
Using the import function of CTFNote will not work if the uploaded data contains tasks that have already been imported.
This is typically encountered when importing challenges once and importing an updated list of challenges after new tasks are released.

**Steps to reproduce**
1. Import the following data:
```
foo|foo
```

2. Import the following data:
```
foo|foo
bar|bar
```

3. `bar` is not imported because `foo` already exists

**Logs**
This happened on commit a0f94e1a4864f22eaa7f51e8b21f999d0976ac60 (current master)
```
db_1      | 2021-03-20 17:46:16.487 UTC [231] ERROR:  duplicate key value violates unique constraint "UQ_7e28b6f481038cc247d976df847"
db_1      | 2021-03-20 17:46:16.487 UTC [231] DETAIL:  Key ("ctfId", slug)=(1, welcome) already exists.
db_1      | 2021-03-20 17:46:16.487 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.490 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.490 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.493 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.493 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.495 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.495 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.498 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.498 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.499 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.499 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.502 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.502 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.504 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.504 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.506 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.506 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.508 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.508 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.511 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.511 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.513 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.513 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
db_1      | 2021-03-20 17:46:16.515 UTC [231] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1      | 2021-03-20 17:46:16.515 UTC [231] STATEMENT:  UPDATE "task" SET "ctfId" = $2 WHERE "id" = $1
api_1     | (node:1) UnhandledPromiseRejectionWarning: QueryFailedError: duplicate key value violates unique constraint "UQ_7e28b6f481038cc247d976df847"
api_1     |     at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
api_1     |     at Query.callback (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:235:38)
api_1     |     at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:128:19)
api_1     |     at Client._handleErrorMessage (/usr/src/app/node_modules/pg/lib/client.js:335:17)
api_1     |     at Connection.emit (events.js:314:20)
api_1     |     at /usr/src/app/node_modules/pg/lib/connection.js:115:12
api_1     |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:40:17)
api_1     |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:10:42)
api_1     |     at Socket.emit (events.js:314:20)
api_1     |     at addChunk (_stream_readable.js:304:12)
api_1     | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by SakiiR** [comment]
This is fixed on main :)
